package tui

var helpLines = []string{
	"Keyboard shortcuts",
	"  Ctrl+C        Cancel turn / double-tap to quit",
	"  Ctrl+E        Open external editor",
	"  Ctrl+H        Toggle this help",
	"  Ctrl+]        Focus next session",
	"  Ctrl+[        Focus prev session",
	"  PgUp/PgDown   Scroll chat (or this help)",
	"  Up/Down       Scroll this help",
	"  Enter         Submit input / toggle tool detail",
	"  c             Copy entry to clipboard (when browsing)",
	"  Alt+Enter     Insert newline",
	"  Tab           Autocomplete / confirm file search",
	"  Esc           Close overlay / cancel",
	"  @             File search",
	"",
	"Slash commands",
	"  /help         Show this help",
	"  /new          Start a new session",
	"  /resume       Resume a past session",
	"  /yolo         Toggle YOLO mode (skip approvals)",
	"  /endpoint     Switch endpoint",
	"  /model        Switch model",
	"  /cancel       Cancel current turn",
	"  /tokens       Show token usage",
	"  /quit         Quit gohome",
	"",
	"CLI flags",
	"  --endpoint    Endpoint name override",
	"  --model       Model override",
	"  --yolo        Disable all approval prompts",
	"  --resume      Resume most recent session",
	"  --version     Print version and exit",
}
